config/routes.rb
Rails.application.routes.draw do
  root 'search#new'
  get 'search/results'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def new
  end

  def results
    results = HTTParty.get("http://api.openweathermap.org/data/2.5/weather?q=#{params[:zipcode]}&APPID=#{Figaro.env.open_map_api_key}&units=imperial")

    if results.code == 200
    #conditions
    @name = results['name']
    @description = results['weather'].first['description']
    @temp = results['main']['temp']
    @temp_high = results['main']['temp_max']
    @temp_low = results['main']['temp_min']
    @humidity = results['main']['humidity']
    @icon = results['weather'].first['icon']
  else
    @error_message = results['message']
  end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weatherdex</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/darkly/bootstrap.min.css">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="/"><i class="fa fa-thermometer-three-quarters"></i> Weatherdex</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      </div>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
    <hr>
    <footer id="mainfooter">
      Darius Seals Copyright &copy; 2019 <br>
    <a href="https://www.linkedin.com/in/dariusseals/" target="_blank">
      <i class="fab fa-linkedin" id="icons"></i>
    </a>
    <a href="https://github.com/Dseals82" target="_blank">
      <i class="fab fa-github" id="icons"></i>
    </a>
  </footer>
  </div>
</body>
</html>

app/views/search/_form.html.erb
<%= form_tag(search_results_path, method: :get) do %>
  <%= text_field_tag :zipcode, nil, placeholder: 'City, State and Zipcode', autofocus: true, class:'form-control'%><br>
  <%= submit_tag 'Get Weather', class: 'btn btn-success' %>
<%end%>

app/views/search/new.html.erb
<div class="jumbotron">
  <h1 align = 'center' >Search Weather <i class="fa fa-thermometer-three-quarters"  id="therma"></i></h1>
  <p align = 'center'>Enter the name of a city!</p>

  <%= render 'form'%>
</div>

app/views/search/results.html.erb
<div class="jumbotron">
<h1 align = 'center'>Results for <%= @name %></h1>
  <% if @error_message.nil?%>
  <div align ='center'class="">
    <h2><%= @description%> <%=image_tag "http://openweathermap.org/img/w/#{@icon}.png"%></h2>
    <h1><%= @temp%>&deg;</h1>
    <h2><%= @humidity%> % Humidity</h2>
    <h4>High: <%=@temp_high %>&deg;F / Low: <%= @temp_low%>&deg;</h4>
  </div>
  <%else%>
  <div class="alert alert-danger" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%=@error_message%>
  </div>
  <%end%>
  <h3>Search another city?</h3>
  <%= render 'form'%>
</div>